import test from "node:test";
import assert from "node:assert/strict";
import {WebInput} from "../.test-build/platform/web/WebInput.js";
import {GameSession} from "../.test-build/gameplay/GameSession.js";
const key=(input,code,down)=>input[down?"keyDown":"keyUp"]({code,preventDefault(){}});

const setup=()=>{
 const input=new WebInput({});
 const session=new GameSession(input);
 session.setMode("local-pvp");
 return {input,session};
};
test("local PvP spawns two human fighters with symmetrical base health and no bot",()=>{
 const {input,session}=setup();
 const view=session.getRenderState();
 assert.equal(view.mode,"local-pvp");
 assert.equal(view.player.health,100);
 assert.equal(view.opponent.health,100);
 assert.equal(view.opponent.enemyType,null);
 assert.equal(session.getHudState().secondWeapon,"blade");
 assert.equal(input.getPlayer2State().attackHeld,false);
 session.dispose();
});
test("independent WASD/Arrow inputs drive simultaneous movement and jumping",()=>{
 const {input,session}=setup();
 key(input,"KeyD",true);
 key(input,"ArrowLeft",true);
 session.update(1/60);
 const moving=session.getRenderState();
 assert.ok(moving.player.velocityX>0);
 assert.ok(moving.opponent.velocityX<0);
 key(input,"KeyW",true);
 key(input,"ArrowUp",true);
 session.update(1/60);
 const jumping=session.getRenderState();
 assert.ok(jumping.player.velocityY>0);
 assert.ok(jumping.opponent.velocityY>0);
 key(input,"KeyD",false);key(input,"ArrowLeft",false);
 key(input,"KeyW",false);key(input,"ArrowUp",false);
 session.dispose();
});
test("P2 attack, hold, release and weapon switching never modify the P1 input state",()=>{
 const {input,session}=setup();
 key(input,"Enter",true);
 assert.equal(input.getPlayer2State().attackPressed,true);
 assert.equal(input.getState().attackPressed,false);
 session.update(1/60);
 assert.ok(session.opponent.cooldown>0);
 assert.equal(session.player.cooldown,0);
 key(input,"Enter",false);
 input.endFrame();
 assert.equal(input.getPlayer2State().attackHeld,false);
 key(input,"BracketRight",true);
 session.update(1/60);
 assert.equal(session.getHudState().secondWeapon,"hammer");
 assert.equal(session.getHudState().weapon,"blade");
 key(input,"BracketRight",false);
 session.dispose();
});
test("P2 Bow charge fires only on actual release and cancelled charges never fire",()=>{
 const {input,session}=setup();
 for(let i=0;i<5;i++)session.selectPlayer2Weapon(1);
 assert.equal(session.opponent.weapon,"bow");
 input.player2TouchAttackStart();
 for(let i=0;i<10;i++)session.update(1/60);
 assert.ok(session.opponent.bowCharge>0);
 assert.equal(session.projectiles.filter(p=>p.owner==="opponent"&&p.weapon==="bow").length,0);
 input.player2TouchAttackCancel();
 session.update(1/60);
 assert.equal(session.opponent.bowCharging,false);
 assert.equal(session.projectiles.filter(p=>p.owner==="opponent"&&p.weapon==="bow").length,0);
 input.player2TouchAttackStart();
 for(let i=0;i<10;i++)session.update(1/60);
 input.player2TouchAttackRelease();
 session.update(1/60);
 assert.equal(session.projectiles.filter(p=>p.owner==="opponent"&&p.weapon==="bow").length,1);
 session.dispose();
});
test("independent P2 touch joystick and automatic UZI do not arm P1",()=>{
 const {input,session}=setup();
 for(let i=0;i<3;i++)session.selectPlayer2Weapon(1);
 assert.equal(session.opponent.weapon,"uzi");
 input.setPlayer2TouchMove(-.75,-.8);
 assert.equal(input.getPlayer2State().jumpPressed,true);
 assert.equal(input.getState().jumpPressed,false);
 assert.equal(input.getState().moveX,0);
 input.player2TouchAttackStart();
 for(let i=0;i<36;i++)session.update(1/60);
 assert.ok(session.projectiles.some(p=>p.owner==="opponent"&&p.weapon==="uzi"));
 assert.equal(input.getState().attackHeld,false);
 input.player2TouchAttackRelease();
 assert.equal(input.getPlayer2State().attackHeld,false);
 input.setPlayer2TouchMove(0,0);
 assert.equal(input.getPlayer2State().moveX,0);
 session.dispose();
});
test("both sides can win, double KO is a draw, and PvP never grants career upgrade points",()=>{
 const {session}=setup();
 const points=session.getHudState().upgradePoints;
 session.damage(session.opponent,200,0);
 session.update(1/60);
 assert.equal(session.getHudState().winner,"player");
 assert.equal(session.getHudState().upgradePoints,points);
 session.reset(false);
 session.damage(session.player,200,0);
 session.update(1/60);
 assert.equal(session.getHudState().winner,"opponent");
 assert.equal(session.getHudState().upgradePoints,points);
 session.reset(false);
 session.damage(session.player,200,0);
 session.damage(session.opponent,200,0);
 session.update(1/60);
 assert.equal(session.getHudState().winner,"draw");
 assert.equal(session.getHudState().upgradePoints,points);
 session.dispose();
});
test("choosing a new arena and rematching retain local PvP; returning to Duel restores AI",()=>{
 const {input,session}=setup();
 session.setArena("fortress");
 assert.equal(session.getRenderState().arena,"fortress");
 assert.equal(session.getRenderState().opponent.enemyType,null);
 assert.equal(session.getHudState().weapon,"blade","Fortress PvP does not force missile rules");
 session.selectPlayer2Weapon(1);
 assert.equal(session.getHudState().secondWeapon,"hammer");
 session.reset();
 assert.equal(session.getHudState().winner,null);
 assert.equal(session.getHudState().secondWeapon,"blade");
 assert.equal(session.getRenderState().opponent.enemyType,null);
 session.setMode("duel");
 assert.equal(session.getRenderState().opponent.enemyType,"runner");
 assert.equal(input.getPlayer2State().attackHeld,false);
 session.dispose();
});
