import type {Renderer} from "./Renderer";
import type {GameRenderState,DuelistRenderState} from "../gameplay/GameSession";
export class CanvasRenderer implements Renderer{
 private readonly context:CanvasRenderingContext2D;private width=1;private height=1;private dpr=1;
 constructor(private readonly canvas:HTMLCanvasElement){const c=canvas.getContext("2d");if(!c)throw new Error("2D canvas rendering is unavailable.");this.context=c;this.resize();}
 resize(){this.width=Math.max(1,this.canvas.clientWidth);this.height=Math.max(1,this.canvas.clientHeight);this.dpr=Math.min(window.devicePixelRatio||1,2);this.canvas.width=Math.floor(this.width*this.dpr);this.canvas.height=Math.floor(this.height*this.dpr);}
 render(state:GameRenderState){const c=this.context;c.setTransform(this.dpr,0,0,this.dpr,0,0);c.fillStyle="#000";c.fillRect(0,0,this.width,this.height);const vh=10,vw=vh*this.width/Math.max(1,this.height),scale=this.height/vh,toX=(x:number)=>(x+vw/2)*scale,toY=(y:number)=>(2+vh/2-y)*scale;c.fillStyle="#777";for(const p of state.platforms)c.fillRect(toX(p.x),toY(p.y+p.height),p.width*scale,p.height*scale);this.draw(c,state.player,toX,toY,scale);this.draw(c,state.opponent,toX,toY,scale);c.fillStyle="#fff";for(const p of state.projectiles){c.beginPath();c.arc(toX(p.x),toY(p.y),Math.max(2,scale*.09),0,Math.PI*2);c.fill();}}
 private draw(c:CanvasRenderingContext2D,s:DuelistRenderState,toX:(x:number)=>number,toY:(y:number)=>number,scale:number){const x=toX(s.x),y=toY(s.y),dir=s.facing;c.strokeStyle="#fff";c.fillStyle="#fff";c.lineWidth=Math.max(2,scale*.06);c.lineCap="round";c.beginPath();c.arc(x,y-.82*scale,.24*scale,0,Math.PI*2);c.fill();const hip=y+.08*scale,shoulder=y-.42*scale,foot=y+.9*scale;c.beginPath();c.moveTo(x,hip);c.lineTo(x,shoulder);c.moveTo(x,hip);c.lineTo(x+dir*-.28*scale,foot);c.moveTo(x,hip);c.lineTo(x+dir*.28*scale,foot);c.moveTo(x+dir*-.22*scale,shoulder);c.lineTo(x+dir*-.42*scale,y);c.moveTo(x+dir*.22*scale,shoulder);c.lineTo(x+dir*.42*scale,y);if(s.attackTime>0){c.moveTo(x+dir*.3*scale,y);c.lineTo(x+dir*1.05*scale,y-.05*scale);}c.stroke();}
 dispose(){}
}